### PR TITLE
Redesign sign-in screen - Closes #1133

### LINKED ISSUE #1133: Update automatic Sign-in design
### Description
Currently, the login screen design has the feel of Biometric login is already being triggered. We need to separate this to a different screen for a better user experience

### Acceptance Criteria
- When a user clicks Login with Face or Touch ID, the app should show animation for respective biometric options
- When there's an error in login, the app should go back to the previous screen to allow user select option to login with password or biometric option.
- Make sure app design is matching the proposed design
Screenshot 2021-11-16 at 14 55 29

### PR DESCRIPTION
**Pull request by Balanced02**
### What was the problem?
This PR resolves #1133

### How was it solved?
Update SignIn Design to match proposed design

### How was it tested?
Tested on both android and ios simulator

### CODE REVIEW

**Review by ManuGowda — APPROVED** [review]
Apart from the `choose an authentication method` text alignment for small screen, rest looks good

**Comment by ManuGowda** [comment]
@Balanced02 u have one unverified commit, can u verify it?

**Comment by Balanced02** [comment]
> Apart from the `choose an authentication method` text alignment for small screen, rest looks good

@ManuGowda, Can you pls provide screenshot of this so I'll be sure what you're referring to pls?

**Comment by ManuGowda** [comment]
image

@Balanced02 the iPhone 8 design needs to be more aligned with 12 design (the space between illustration, use the space in header and footer similar to 12)

**Comment by ManuGowda** [comment]
Screenshot 2021-11-20 at 15 23 42

marked the comments in black and blue colour.. also the middle image is the design I referred.. please address these comments

**Review by ManuGowda — APPROVED** [review]

**Pull request merged**
