### PR TITLE
Add e2e to jenkins - Closes #837

### LINKED ISSUE #837: Add lisk mobile e2e tests to the jeckins flow
### Expected behaviour
Jenkins should run end to end tests on after each commit on GitHub.
### Actual behaviour
Jenkins doesn't run end to end tests

### PR DESCRIPTION
**Pull request by Efefefef**
# What was the bug or feature?
Make e2e run on Jenkins for every commit

## Type of change
- Test

### How to test it?
Check if tests on Jenkins are passing and green

# Checklist:
- My code follows the style guidelines of this project
- I have performed a self-review of my own code
- I have commented my code, particularly in hard-to-understand areas
- I have made corresponding changes to the documentation
- I have added tests that prove my fix is effective or that my feature works
- New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by fchavant** [comment]
@Efefefef unit tests fail (["No tests found"](https://jenkins.lisk.io/blue/organizations/jenkins/lisk-mobile/detail/837-add-e2e-to-jenkins/1/pipeline/)); can you have a look?

**Comment by Efefefef** [comment]
@fchavant I've managed to make the `npm run test:build-e2e-release` build successfully on the local machine ( using nvm and the same version of node) instead `npm run test:build-e2e-debug`
Can we try to make it run on the Jenkins attached mac? 
It is supposed to run a release build on the CI and could potentially give us some timing advantage.

**Comment by Efefefef** [comment]
@reyraa Font files are missing. We need some sort of a solution

**Comment by fchavant** [comment]
How about installing the fonts system-wide (and making that a prerequisite?)
Alternatively we could download the fonts in the `Jenkinsfile`.

**Pull request merged**
